#!/usr/bin/env python3
"""Tool to search and display artifacts generated by the Antigravity CLI
(~/.gemini/antigravity-cli).

Artifacts are stored under the brain directory, in one UUID-named directory
per conversation. Each artifact directly under such a directory has a
sidecar named <filename>.metadata.json (summary, updatedAt, etc); this is
how artifacts are discovered, regardless of their own extension. This tool
lists and displays those artifacts.

Usage:
    agyfind summary [DIRECTORY]   list entries as "N. YYYY/MM/DD HH:mm:SS [workspace] summary"
    agyfind ls [DIRECTORY]        list artifact file paths
    agyfind show N [-n LINES] [--no-pager] [--no-rich]
                                  show details of summary entry N (content is limited to LINES lines)
    agyfind copy N [-n LINES] [--show] [--zenn]
                                  copy the content of entry N to the clipboard

`show` renders the content as Markdown with rich and, like `git show`, pipes
it through a pager ($PAGER, or less by default) when stdout is a terminal.
When paging, colors are always emitted. Use --no-pager to print directly
(rich then decides whether to use colors); this is implied when stdout is
piped or redirected. Use --no-rich to print plain text.

`copy` puts the content shown by `show --no-rich` (without the header, and
with trailing whitespace stripped) on the clipboard via wl-copy (pyperclip is
unreliable in some environments). Local links (file:///...) pointing into a
git repository with a GitHub remote are rewritten to the corresponding GitHub
web URL, so the text can be shared as is. Other Markdown links to file:///...
are dropped, keeping only their text. With --show, the copied text is also
printed (through the pager, as with `show`). With --zenn, GitHub alerts
(> [!NOTE] etc.) are converted to Zenn's :::message (:::message alert for
WARNING).

If DIRECTORY is given, only conversations belonging to that working
directory (the ~/... part of a summary line) are shown. In that case the
workspace is omitted from summary lines (since it would be identical on
every line).

Sources of information:
    - brain/<UUID>/<file>.metadata.json ... summary
    - brain/<UUID>/<file> ... the artifact itself; its mtime is used as the update time
      (updatedAt in the metadata is not refreshed on edits, so it is ignored)
    - conversation_summaries.db ... mapping from conversation_id to working directory (official source)
    - history.jsonl ... same mapping from input history, used to fill gaps when the DB
      has not yet caught up with the latest conversation

Entries are always sorted by the artifact's mtime (converted to JST) in descending
order. The index number in `agyfind summary` reflects this order across the
full, unfiltered entry list, so it stays valid for `agyfind show N` even
when `agyfind summary DIRECTORY` narrows what's displayed.
"""

import argparse
import json
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import unicodedata
import urllib.parse
from datetime import datetime, timedelta, timezone
from pathlib import Path

from . import __version__

BASE_DIR = Path.home() / ".gemini" / "antigravity-cli" / "brain"
SUMMARIES_DB = Path.home() / ".gemini" / "antigravity-cli" / "conversation_summaries.db"
HISTORY_JSONL = Path.home() / ".gemini" / "antigravity-cli" / "history.jsonl"
# Japan has no DST, so JST is represented as a fixed offset without relying on tzdata
JST = timezone(timedelta(hours=9))
STAMP_WIDTH = 20  # "YYYY/MM/DD HH:mm:SS "
# Directly under brain are per-conversation UUID directories. This pattern is
# used to exclude any other directories/files.
UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", re.IGNORECASE)
# A file:// URL as it appears in Markdown: bare, in (...) of a link, or in <...>
FILE_URL_RE = re.compile(r"file://[^\s()<>\[\]\"'`]+")
# A Markdown link to a file:// URL: [text](file:///...)
FILE_LINK_RE = re.compile(r"\[([^\]\n]*)\]\((" + FILE_URL_RE.pattern + r")\)")
# Remote URLs of GitHub, e.g. git@github.com:OWNER/REPO.git,
# https://github.com/OWNER/REPO.git or ssh://git@github.com/OWNER/REPO
# The first line of a GitHub alert, e.g. "> [!NOTE]"
ALERT_RE = re.compile(r"^>\s*\[!([A-Za-z]+)\]\s*$")
GITHUB_REMOTE_RE = re.compile(r"github\.com[:/]([^/\s]+)/([^/\s]+?)(?:\.git)?/?$")


def display_width(s: str) -> int:
    # Count terminal display width. East Asian wide/fullwidth characters occupy 2 columns
    return sum(2 if unicodedata.east_asian_width(c) in "WF" else 1 for c in s)


def trim(s: str, max_width: int) -> str:
    if display_width(s) <= max_width:
        return s
    out = []
    w = 0
    for c in s:
        cw = 2 if unicodedata.east_asian_width(c) in "WF" else 1
        # max_width - 3 reserves room for the trailing "..."
        if w + cw > max_width - 3:
            break
        out.append(c)
        w += cw
    return "".join(out) + "..."


def terminal_width() -> int:
    # When piped, get_terminal_size() falls back to 80 regardless of the
    # actual width, causing unwanted trimming. For non-tty output, only use
    # COLUMNS as a hint; if unset (0), don't trim (print full text)
    if sys.stdout.isatty():
        return shutil.get_terminal_size().columns
    return int(os.environ.get("COLUMNS") or 0)


def page(text: str) -> None:
    # Mimic git: only page when stdout is a terminal, and let an empty PAGER
    # or "cat" mean "no pager". LESS=FRX makes less exit immediately if the
    # text fits on one screen (F), keep ANSI colors raw (R), and not clear the
    # screen on exit (X). Respect a user-set LESS as git does
    pager = os.environ.get("PAGER", "less")
    if not sys.stdout.isatty() or pager.strip() in ("", "cat"):
        sys.stdout.write(text)
        return
    env = dict(os.environ)
    env.setdefault("LESS", "FRX")
    try:
        # shell=True so PAGER may carry arguments (e.g. "less -S")
        proc = subprocess.Popen(pager, shell=True, stdin=subprocess.PIPE, env=env)
    except OSError:
        sys.stdout.write(text)
        return
    try:
        proc.stdin.write(text.encode(sys.stdout.encoding or "utf-8", errors="replace"))
        proc.stdin.close()
    except BrokenPipeError:
        # The user quit the pager before reading everything
        pass
    # Ctrl-C belongs to the pager while it runs; keep waiting for it to exit
    while True:
        try:
            proc.wait()
            break
        except KeyboardInterrupt:
            pass


def git(cwd: Path, *args: str) -> str | None:
    try:
        proc = subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True)
    except OSError:
        return None
    return proc.stdout.strip() if proc.returncode == 0 else None


def github_repo(toplevel: Path) -> str | None:
    # Return "https://github.com/OWNER/REPO" for a repository whose remote is
    # on GitHub. origin is preferred; otherwise the first GitHub remote wins
    out = git(toplevel, "remote", "-v")
    if not out:
        return None
    urls = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and (m := GITHUB_REMOTE_RE.search(parts[1])):
            urls.setdefault(parts[0], f"https://github.com/{m[1]}/{m[2]}")
    return urls.get("origin") or next(iter(urls.values()), None)


def github_links(text: str) -> str:
    # Rewrite file:// URLs pointing into a git repository with a GitHub remote
    # to the GitHub web URL on the currently checked-out branch, assuming it
    # has been pushed. In detached HEAD state there is no branch name, so HEAD
    # (the default branch on GitHub) is used instead.
    # Fragments like #L10-L20 use the same format on GitHub and are kept.
    # A Markdown link whose URL can't be mapped is useless outside this
    # machine, so the link is dropped and only its text is kept. Other
    # (bare) URLs that can't be mapped are left untouched
    cache: dict[Path, tuple[Path, str, str] | None] = {}

    def to_github(url: str) -> str | None:
        parsed = urllib.parse.urlsplit(url)
        if parsed.netloc not in ("", "localhost"):
            return None
        path = Path(urllib.parse.unquote(parsed.path))
        # The file may have been moved or deleted since; look up the repository
        # from the nearest existing directory
        d = path if path.is_dir() else path.parent
        while not d.is_dir() and d != d.parent:
            d = d.parent
        if d not in cache:
            top = git(d, "rev-parse", "--show-toplevel")
            repo = github_repo(Path(top)) if top else None
            branch = (git(d, "branch", "--show-current") or "HEAD") if repo else ""
            cache[d] = (Path(top), repo, branch) if repo else None
        if not cache[d]:
            return None
        top, repo, branch = cache[d]
        # toplevel is a real path, so resolve symlinks in the link as well
        try:
            rel = Path(os.path.realpath(path)).relative_to(top)
        except ValueError:
            return None
        kind = "tree" if path.is_dir() else "blob"
        out = f"{repo}/{kind}/{urllib.parse.quote(branch)}"
        if rel.parts:
            out += "/" + urllib.parse.quote(rel.as_posix())
        if parsed.fragment:
            out += "#" + parsed.fragment
        return out

    def repl_link(m: re.Match) -> str:
        gh = to_github(m[2])
        return f"[{m[1]}]({gh})" if gh else m[1]

    def repl_url(m: re.Match) -> str:
        return to_github(m[0]) or m[0]

    return FILE_URL_RE.sub(repl_url, FILE_LINK_RE.sub(repl_link, text))


def zenn_alerts(text: str) -> str:
    # Convert GitHub alerts to Zenn's message blocks:
    #   > [!NOTE]          :::message
    #   > body       ->    body
    #                      :::
    # WARNING becomes ":::message alert" (Zenn's warning style). The alert ends at the first line that doesn't start with ">". Lines
    # inside fenced code blocks are left as is
    out = []
    fence = None
    in_alert = False
    for line in text.splitlines():
        if in_alert:
            if line.startswith(">"):
                out.append(line[2:] if line.startswith("> ") else line[1:])
                continue
            out.append(":::")
            in_alert = False
        if fence:
            if line.startswith(fence):
                fence = None
        elif line.startswith(("```", "~~~")):
            fence = line[:3]
        elif m := ALERT_RE.match(line):
            out.append(":::message alert" if m[1].upper() == "WARNING" else ":::message")
            in_alert = True
            continue
        out.append(line)
    if in_alert:
        out.append(":::")
    return "\n".join(out) + "\n"


def shorten_home(s: str) -> str:
    home = os.environ.get("HOME")
    if home and s == home:
        return "~"
    # Compare with a trailing "/" so /home/USER doesn't falsely match /home/USER_
    if home and s.startswith(home + "/"):
        return "~" + s[len(home):]
    return s


def load_workspaces() -> dict[str, str]:
    # Build a mapping from conversation_id to working directory.
    # 1) conversation_summaries.db: the official mapping. workspace_uris is a
    #    JSON array of file:// URIs, usually with a single element
    # 2) history.jsonl: the DB may not yet reflect the latest conversation due
    #    to write timing, so this fills the gap. Entries already in the DB
    #    take priority over history.jsonl
    workspaces = {}
    try:
        # Open read-only to avoid accidental writes
        con = sqlite3.connect(f"file:{SUMMARIES_DB}?mode=ro", uri=True)
        try:
            rows = con.execute("SELECT conversation_id, workspace_uris FROM conversation_summaries")
            for cid, uris in rows:
                try:
                    uris = json.loads(uris)
                    workspaces[cid] = uris[0].removeprefix("file://") if uris else ""
                except (json.JSONDecodeError, AttributeError, TypeError):
                    workspaces[cid] = ""
        finally:
            con.close()
    except (sqlite3.Error, OSError):
        pass
    try:
        with HISTORY_JSONL.open() as f:
            for line in f:
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                cid = rec.get("conversationId")
                ws = rec.get("workspace")
                if cid and ws and cid not in workspaces:
                    workspaces[cid] = ws
    except OSError:
        pass
    return workspaces


def load_entries() -> list[tuple[datetime, str, Path]]:
    # Scan *.metadata.json sidecars directly under each conversation
    # directory, then resolve the artifact file they describe. This way the
    # artifact's own extension doesn't matter (not just *.md).
    # Subdirectories like .system_generated/ or scratch/ hold internal
    # artifacts (with no metadata) and shouldn't appear in the listing
    entries = []
    for conv_dir in BASE_DIR.iterdir():
        if not conv_dir.is_dir() or not UUID_RE.match(conv_dir.name):
            continue
        for meta_path in conv_dir.glob("*.metadata.json"):
            p = meta_path.with_name(meta_path.name.removesuffix(".metadata.json"))
            if not p.is_file():
                continue
            summary = ""
            try:
                meta = json.loads(meta_path.read_text())
                summary = meta.get("summary") or ""
            except (OSError, json.JSONDecodeError):
                pass
            # Use the artifact's own mtime: updatedAt in the metadata is not
            # refreshed when the artifact is edited
            updated = datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc)
            entries.append((updated, summary, p))
    entries.sort(key=lambda e: e[0], reverse=True)
    return entries


def show_rich(header: list[str], lines: list[str], force_terminal: bool = False) -> str | None:
    # Render the header and content with rich. With force_terminal, the
    # output is captured and returned as a string (with ANSI colors) instead
    # of being printed.
    # Imported lazily so the plain commands don't pay rich's import cost
    from rich.console import Console
    from rich.markdown import Markdown
    from rich.rule import Rule

    console = Console(force_terminal=True) if force_terminal else Console()
    # The "---" delimiters are drawn as rules styled like a Markdown
    # horizontal rule. The header lines between them are printed as is
    #hr = Rule(style="markdown.hr", characters="-")
    hr = Rule(style="markdown.hr")

    def render() -> None:
        console.print(hr)
        console.out("\n".join(header), highlight=False)
        console.print(hr)
        console.print()
        console.print(Markdown("\n".join(lines)))

    if not force_terminal:
        render()
        return None
    with console.capture() as capture:
        render()
    return capture.get()


def main() -> int:
    parser = argparse.ArgumentParser(prog="agyfind", description="find files in Antigravity CLI artifacts")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    for name, help_text in (
        ("summary", "show 'YYYY/MM/DD HH:mm:SS summary'"),
        ("ls", "show artifact file paths"),
    ):
        p = sub.add_parser(name, help=help_text)
        p.add_argument("directory", nargs="?", default=None, help="filter by workspace directory (e.g. ~/repos/opencode)")

    p = sub.add_parser("show", help="show entry details (head of content)")
    p.add_argument("index", type=int, help="entry number shown by summary (1-based)")
    p.add_argument("-n", dest="lines", type=int, default=None, help="number of content lines (default: all)")
    p.add_argument("--no-pager", action="store_true", help="do not pipe output into a pager")
    p.add_argument("--no-rich", action="store_true", help="print plain text instead of rendering Markdown with rich")

    p = sub.add_parser("copy", help="copy entry details to the clipboard (file:// links become GitHub URLs)")
    p.add_argument("index", type=int, help="entry number shown by summary (1-based)")
    p.add_argument("-n", dest="lines", type=int, default=None, help="number of content lines (default: all)")
    p.add_argument("--show", action="store_true", help="also print the copied text")
    p.add_argument("--zenn", action="store_true", help="convert GitHub alerts (> [!NOTE] etc.) to Zenn's :::message")

    args = parser.parse_args()

    entries = load_entries()
    workspaces = load_workspaces()
    width = terminal_width()
    # Combined width of the index number (right-aligned) + "." + space + timestamp + space
    # Based on the full (unfiltered) entry count, since indices refer to
    # positions in that list and must stay valid for `show` even when a
    # directory filter narrows what's displayed here
    num_width = len(str(len(entries)))
    prefix_width = num_width + 2 + STAMP_WIDTH

    # Pair each entry with its 1-based index in the full, unfiltered list.
    # This index is what `show N` expects, so it must be preserved even when
    # filtering below narrows which entries are displayed
    indexed_entries = list(enumerate(entries, 1))

    # The argument filters by the workspace part (the conversation's working
    # directory) shown in summary lines. expanduser expands ~, and resolve
    # normalizes a relative path (including . or ..) to an absolute path
    # before comparison.
    # In addition to an exact match, descendants of the given directory are
    # also matched by prefix
    dir_filter = None
    # If every matched workspace equals the given directory exactly, showing
    # it would be redundant, so hide it. If subdirectories are included (i.e.
    # values differ per line), show it everywhere for clarity.
    # This is a single flag for the whole output rather than toggled per line
    show_ws = True
    if args.command in ("summary", "ls") and args.directory:
        dir_filter = str(Path(args.directory).expanduser().resolve())
        indexed_entries = [
            (i, e) for i, e in indexed_entries
            if (ws := workspaces.get(e[2].relative_to(BASE_DIR).parts[0], ""))
            and (ws == dir_filter or ws.startswith(dir_filter + "/"))
        ]
        show_ws = any(workspaces.get(e[2].relative_to(BASE_DIR).parts[0], "") != dir_filter for _, e in indexed_entries)

    # When displaying the workspace, compute the max display width up front
    # so columns line up across all rows
    ws_width = 0
    if args.command == "summary" and show_ws:
        ws_width = max(
            (
                display_width(shorten_home(workspaces.get(p.relative_to(BASE_DIR).parts[0], "")))
                for _, (_, _, p) in indexed_entries
            ),
            default=0,
        )

    if args.command in ("show", "copy"):
        n = args.index
        if not 1 <= n <= len(entries):
            print(f"agyfind: index out of range: {n} (1..{len(entries)})", file=sys.stderr)
            return 1
        updated, summary, path = entries[n - 1]
        conv_id = path.relative_to(BASE_DIR).parts[0]
        ws = shorten_home(workspaces.get(conv_id, ""))
        try:
            text = path.read_text(errors="replace")
        except OSError as exc:
            print(f"agyfind: cannot read {path}: {exc}", file=sys.stderr)
            return 1
        # Build the whole output first so it can be handed to the pager at once.
        # The header is plain "key: value" lines enclosed in "---" (like front
        # matter, but values are not quoted, so it isn't guaranteed to be YAML)
        header = [
            f"path: {shorten_home(str(path))}",
            f"updated: {updated.astimezone(JST).replace(microsecond=0).isoformat(sep=' ')}",
        ]
        if ws:
            header.append(f"workspace: {ws}")
        if summary:
            header.append(f"summary: {summary}")
        out = ["---", *header, "---", ""]
        lines = text.splitlines()
        if args.lines is not None:
            lines = lines[: max(0, args.lines)]
        if args.command == "copy":
            # Only the content is copied, without the header, so it can be
            # pasted into another document as is
            output = github_links("\n".join(lines))
            if args.zenn:
                output = zenn_alerts(output)
            output = output.rstrip() + "\n"
            try:
                subprocess.run(["wl-copy"], input=output.encode(), check=True)
            except (OSError, subprocess.CalledProcessError) as exc:
                print(f"agyfind: wl-copy failed: {exc}", file=sys.stderr)
                return 1
            print(f"agyfind: copied entry {n} to the clipboard", file=sys.stderr)
            if args.show:
                try:
                    page(output)
                except BrokenPipeError:
                    os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
            return 0
        # Like git, don't page when stdout is piped or redirected
        no_pager = args.no_pager or not sys.stdout.isatty()
        try:
            if args.no_rich:
                out.extend(lines)
                output = "\n".join(out) + "\n"
                if no_pager:
                    sys.stdout.write(output)
                else:
                    page(output)
            elif no_pager:
                # Print directly with rich, letting it detect the terminal
                show_rich(header, lines)
            else:
                # Render with rich into a string with colors forced on, and
                # hand it to the pager (less -R shows them)
                page(show_rich(header, lines, force_terminal=True))
        except BrokenPipeError:
            os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
        return 0

    try:
        for i, (updated, summary, p) in indexed_entries:
            if args.command == "summary":
                stamp = updated.astimezone(JST).strftime("%Y/%m/%d %H:%M:%S")
                body = summary or p.name
                if show_ws:
                    conv_id = p.relative_to(BASE_DIR).parts[0]
                    ws = shorten_home(workspaces.get(conv_id, ""))
                    if ws:
                        # Pad with spaces to align columns by display width
                        ws_pad = ws + " " * (ws_width - display_width(ws))
                        body = f"{ws_pad} {body}"
                # Trim the "directory+title" combination as a whole (padding
                # spaces for alignment are preserved)
                if width > prefix_width + 3:
                    body = trim(body, width - prefix_width)
                print(f"{i:>{num_width}d}. {stamp} {body}")
            else:
                print(shorten_home(str(p)))
    except BrokenPipeError:
        # Happens when the pipe is closed early, e.g. by `| head`.
        # Redirect stdout to devnull to avoid a second BrokenPipeError on
        # flush at interpreter shutdown
        os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())

    return 0


if __name__ == "__main__":
    sys.exit(main())
